export interface Service {
    id: string;
    slug: string;
    name: string;
    nameEn: string;
    tagline: string;
    description: string;
    category: string;
    target: string;
    targetAge: string[];
    features: string[];
    pros: string[];
    cons: string[];
    recommended: string[];
    affiliateUrl: string;
    ctaText: string;
    color: string;
}

export const services: Service[] = [
    {
        id: 'skyoffice',
        slug: 'skyoffice',
        name: 'スカイオフィスキャッシング',
        nameEn: 'SKYOFFICE',
        tagline: '来店不要！スピーディーなキャッシング',
        description: 'ネットで簡単申し込み、来店不要のスピードキャッシング。急な出費にも素早く対応。シンプルな手続きで初めての方でも安心して利用できます。',
        category: 'スピードキャッシング',
        target: '来店せずに素早く借りたい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['来店不要のネット申し込み', 'スピーディーな審査・融資', 'シンプルな手続き', '全国どこからでも申込可能'],
        pros: ['来店不要で手軽に申し込める', '審査がスピーディー', '手続きがシンプルでわかりやすい', '全国対応'],
        cons: ['大手と比べ知名度が低い', '限度額が少なめの場合がある', '金利は標準的'],
        recommended: ['来店せずにネットで完結したい人', 'スピーディーな融資を求める人', '手続きをシンプルに済ませたい人', '地方在住の人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+ESV7OQ+20EO+5YJRM',
        ctaText: '詳細を見る',
        color: '#0ea5e9',
    },
    {
        id: 'arco',
        slug: 'arco-system',
        name: 'アルコシステム',
        nameEn: 'ARCO SYSTEM',
        tagline: '新規のお客様大歓迎！柔軟な審査対応',
        description: '新規顧客の獲得に力を入れている消費者金融。初めてのキャッシングでも丁寧な対応で安心。柔軟な審査で、他社で断られた方にも相談に乗ってくれます。',
        category: '新規歓迎キャッシング',
        target: '初めてのキャッシングで不安な人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['新規顧客を積極的にサポート', '柔軟な審査対応', '丁寧なカスタマーサポート', '利用促進キャンペーンあり'],
        pros: ['初めてでも丁寧に対応してくれる', '柔軟な審査基準', '新規キャンペーンがお得', '相談しやすい雰囲気'],
        cons: ['大手に比べ知名度が低い', '融資スピードは大手に劣る場合あり', '利用可能ATMが限られる'],
        recommended: ['初めてキャッシングする人', '他社で審査に落ちた経験がある人', '丁寧な対応を求める人', 'キャンペーンを活用したい人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EROCH6+25IK+601S2',
        ctaText: '詳細を見る',
        color: '#6366f1',
    },
    {
        id: 'nichiden',
        slug: 'nichiden',
        name: 'クレジットのニチデン',
        nameEn: 'NICHIDEN',
        tagline: '簡単・便利！ネットで完結キャッシング',
        description: 'ネットで簡単に申し込めるキャッシングサービス。来店不要で24時間申し込み可能。手軽さと利便性を追求した、忙しい方にぴったりのサービスです。',
        category: 'ネット完結キャッシング',
        target: 'ネットで手軽に借りたい人',
        targetAge: ['20代', '30代', '40代'],
        features: ['ネットで24時間申し込み可能', '来店不要で完結', '簡単な手続き', 'スマホからも申し込みOK'],
        pros: ['24時間いつでも申し込める', 'ネットで全て完結する手軽さ', 'スマホから簡単操作', '忙しい人でも利用しやすい'],
        cons: ['対面でのサポートがない', '知名度が大手より低い', '審査に時間がかかる場合がある'],
        recommended: ['忙しくて来店する時間がない人', 'スマホで全て済ませたい人', '深夜や早朝に申し込みたい人', 'ネット操作に慣れている人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EU22WA+2J9A+60H7M',
        ctaText: '詳細を見る',
        color: '#10b981',
    },
    {
        id: 'arrow',
        slug: 'arrow',
        name: 'アロー',
        nameEn: 'ARROW',
        tagline: '独自審査で柔軟対応！頼れるキャッシング',
        description: '独自の審査基準で柔軟に対応するキャッシングサービス。大手で断られた方にもチャンスあり。一人ひとりの状況に合わせた審査で、借入をサポートします。',
        category: '柔軟審査キャッシング',
        target: '審査に不安がある人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['独自の柔軟な審査基準', '一人ひとりに合わせた対応', '相談しやすい体制', 'スピーディーな審査'],
        pros: ['審査が柔軟で通りやすい', '個別の状況を考慮してくれる', '他社で断られても相談可能', '対応が丁寧'],
        cons: ['金利がやや高めの場合がある', '限度額が小さめ', '知名度は大手に劣る'],
        recommended: ['他社で審査に落ちた人', '審査に不安を感じている人', '柔軟な対応を求める人', '少額の借入を希望する人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EEKT62+2SHI+5YJRM',
        ctaText: '詳細を見る',
        color: '#f59e0b',
    },
    {
        id: 'futaba',
        slug: 'futaba',
        name: 'フタバ',
        nameEn: 'FUTABA',
        tagline: '借りやすくて返しやすい！レディースも対応',
        description: '「借りやすくて返しやすい」がコンセプト。レディースキャッシングにも対応し、女性スタッフによる丁寧な対応が好評。初めての方にも安心の消費者金融です。',
        category: 'レディース対応キャッシング',
        target: '女性や初めての方',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['レディースキャッシング対応', '女性スタッフが丁寧に対応', '借りやすく返しやすい設計', '初めてでも安心'],
        pros: ['女性専用ダイヤルがある', '返済プランが柔軟', '丁寧で安心できる対応', '初めてのキャッシングに最適'],
        cons: ['融資スピードは大手に劣る場合あり', '限度額が控えめ', 'ATM対応が限られる'],
        recommended: ['女性で安心して借りたい人', '初めてキャッシングする人', '返済計画を丁寧に立てたい人', '女性スタッフに相談したい人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EDDXYI+38S6+5ZMCI',
        ctaText: '詳細を見る',
        color: '#ec4899',
    },
    {
        id: 'quick39',
        slug: 'quick39',
        name: 'QUICK39',
        nameEn: 'QUICK39',
        tagline: 'クイック審査でスピード融資！',
        description: '名前の通りスピードが売り。素早い審査と融資で、急な資金ニーズに対応します。シンプルな手続きで、必要な時にスピーディーにお金を借りられます。',
        category: 'スピード融資',
        target: 'とにかく急いでいる人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['クイック審査でスピード対応', 'シンプルな手続き', '急な資金ニーズに対応', '素早い融資実行'],
        pros: ['審査がスピーディー', '手続きが簡単', '急ぎの時に頼りになる', '分かりやすいサービス設計'],
        cons: ['限度額が控えめな場合がある', '大手に比べサービスは限定的', '知名度が低い'],
        recommended: ['今すぐお金が必要な人', '手続きを素早く済ませたい人', 'シンプルなサービスを求める人', '少額の急な出費に対応したい人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+E97WQ2+1A0Y+62U36',
        ctaText: '詳細を見る',
        color: '#ef4444',
    },
    {
        id: 'hello-happy',
        slug: 'hello-happy',
        name: 'ハローハッピー',
        nameEn: 'HELLO HAPPY',
        tagline: '安心できるパートナー。フリーローンで柔軟対応',
        description: '「安心できるパートナー」をモットーに、フリーローンで柔軟に対応。用途を問わずに利用でき、丁寧なサポートで安心感のあるキャッシングサービスです。',
        category: 'フリーローン',
        target: '用途を問わず柔軟に借りたい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['フリーローンで用途自由', '安心のサポート体制', '柔軟な審査対応', '丁寧なカスタマーサービス'],
        pros: ['用途を問わず自由に使える', '安心感のある丁寧な対応', '柔軟に相談に乗ってくれる', 'フリーローンで使い道自由'],
        cons: ['融資に時間がかかる場合がある', '知名度が大手に劣る', '金利は標準的'],
        recommended: ['借入目的が決まっていない人', '安心できるサービスを重視する人', '柔軟な対応を求める人', 'フリーローンを探している人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EAERXM+2EBI+5Z6WY',
        ctaText: '詳細を見る',
        color: '#8b5cf6',
    },
    {
        id: 'central',
        slug: 'central',
        name: 'セントラル',
        nameEn: 'CENTRAL',
        tagline: '来店不要！全国振込キャッシング',
        description: '来店不要で全国どこからでも振込キャッシングが可能。パーソナルクレジットとして、一人ひとりに合わせた融資を提供。地方在住の方にも便利なサービスです。',
        category: '振込キャッシング',
        target: '振込で手軽に借りたい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['来店不要の振込キャッシング', '全国どこからでも利用可能', 'パーソナルな融資対応', '地方在住でもOK'],
        pros: ['来店せず振込で受け取れる', '全国どこでも対応', '個別の状況に合わせた融資', '手続きが手軽'],
        cons: ['振込までに時間がかかる場合がある', '大手と比べ知名度は低い', 'ATM借入には対応していない場合あり'],
        recommended: ['近くに店舗がない地方在住の人', '振込で受け取りたい人', '来店する時間がない人', '全国対応のサービスを探している人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EC72QY+363I+5YJRM',
        ctaText: '詳細を見る',
        color: '#14b8a6',
    },
    {
        id: 'plan',
        slug: 'plan',
        name: 'プラン',
        nameEn: 'PLAN',
        tagline: '24時間いつでも簡単契約！全国対応',
        description: '全国どこからでも24時間いつでも簡単に契約できるキャッシングサービス。時間を気にせず申し込めるので、忙しい方や深夜に急な出費が発生した方にも最適。',
        category: '24時間対応キャッシング',
        target: '時間を気にせず申し込みたい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: ['24時間いつでも申し込み可能', '全国どこからでも対応', '簡単な契約手続き', '深夜・早朝もOK'],
        pros: ['24時間365日申し込める', '全国どこでも利用可能', '手続きが簡単でわかりやすい', '深夜の急な出費にも対応'],
        cons: ['即日融資は営業時間に依存する場合あり', '知名度が大手に劣る', 'サービス内容は限定的'],
        recommended: ['深夜や早朝に申し込みたい人', '全国どこからでも利用したい人', '時間を気にせず手続きしたい人', '簡単な手続きを求める人'],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC7+EB07JE+3FWK+60WN6',
        ctaText: '詳細を見る',
        color: '#f97316',
    },
];

export function getServiceBySlug(slug: string): Service | undefined {
    return services.find((s) => s.slug === slug);
}
